REDIS_HOST=judge0_redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0redis

POSTGRES_HOST=judge0_db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0secret

WORKERS_MAX_WAIT_TIME=10
MAX_QUEUE_SIZE=100
MAX_CPU_TIME_LIMIT=10
MAX_WALL_TIME_LIMIT=20
MAX_MEMORY_LIMIT=524288

ENABLE_WAIT_RESULT=true
ALLOW_ENABLE_WAIT_RESULT=true
